### ISSUE TITLE
AVG prevents Win Executable Download

### ISSUE THREAD

**Issue by MCVenor** [Auburn/FastNoiseLite#108]
Hi Mr.Auburn,

i would like to inform you about a Message i got from my locally installed AVG Antivirus Program.
It shows me this:
![grafik](https://user-images.githubusercontent.com/12583072/216302763-2e9751d8-c98f-490a-b76c-61956676fcb6.png)

I tried Firefox and Edge browsers to make sure its not Firefox itself.
Then i tried to a Second download of another exe , namly the
FastNoiseSIMD_Preview_0.7.exe 
from:
https://github.com/Auburn/FastNoiseSIMD/releases

The second Exe did not throw any errors at all, passed additional scans and runs fine.

The first mentioned Exe can not get passt the Download check.

Since i am fine with the SIMD version, im ok, but i thought i should let you know about this.
(At first i thought its a False-Positive, but im a bit scepctical now that the second exe didnt throw any warnings.)

**Comment by Auburn** [comment]
Fixed in [v1.1.0](https://github.com/Auburn/FastNoiseLite/releases/tag/v1.1.0) with new web app

**Comment by MCVenor** [comment]
Thanks!
