### ISSUE TITLE
Cellular noise always produces a black texture in the c# version

### ISSUE THREAD

**Issue by angelomorgado** [Auburn/FastNoiseLite#110]
Hey! I'm reporting this because I tried generating the texture in the GUI version and it works flawlessly, but, when I try to replicate it in the code it generates a black texture. It works fine in other noise types, but in the cellular version it doesn't. I set up the distancefunction and the returntype correctly so I shouldn't have any problems. Is there anything I should do or is it a bug?

**Comment by Auburn** [comment]
The GUI uses the C# version so there is probably something different with your settings

**Comment by Auburn** [comment]
All the FastNoise noise type outputs are bounded -1.0, 1.0 so if you were only using 0.0, 1.0 you might have seen this issue
