### ISSUE TITLE
Range for perlin noise is -0.5 to 0.5 instead -1 to 1 like simplex noise

### ISSUE THREAD

**Issue by RuchirRaj** [Auburn/FastNoiseLite#111]
After a bit of testing, I have found that range for perlin noise and cubic (I'm not sure about this one) is -0.5 to 0.5 instead of -1 to 1.
I was using the c# version btw.

**Comment by Auburn** [comment]
![image](https://github.com/Auburn/FastNoiseLite/assets/1349548/95e7a637-8a44-471a-ba47-e7f81e6cea1c)
See at the top the min/max value is near 1

**Comment by RuchirRaj** [comment]
When I use the c# script and plot the values, they were always between -0.5 and 0.5 though, so maybe something to do with the c# version? 
https://github.com/Auburn/FastNoiseLite/blob/master/CSharp/FastNoiseLite.cs

**Comment by Auburn** [comment]
The preview tool uses the C# version.

The problem is that you are using a frequency of 10, which will be giving you effectively white noise. You probably want frequency to be like 0.03

**Comment by RuchirRaj** [comment]
> The preview tool uses the C# version.
> 
> The problem is that you are using a frequency of 10, which will be giving you effectively white noise. You probably want frequency to be like 0.03

It's still the same, it doesn't go above 0.48 at any frequency I put in.

**Comment by RuchirRaj** [comment]
If I change the fractal type to rigged it does go to 1 at any frequency so I don't think it's something to do with the frequency

**Comment by Xeaker** [comment]
When I use Perlin I don't get Range from -1 to 1. 
I get like:
https://i.imgur.com/1IBiJaW.png
Sometimes I get only like -0.7 to 0.9

**Comment by chadefranklin** [comment]
> When I use Perlin I don't get Range from -1 to 1. I get like: https://i.imgur.com/1IBiJaW.png Sometimes I get only like -0.7 to 0.9

The range -1 to 1 is the range over the entire domain, not the relatively narrow area of the domain in your linked screenshot.

**Comment by Auburn** [comment]
The range min/max is mathematically calculated to be -1 to 1, depending on the noise type it can be very rare to even get close to the range limits but it is still theoretically possible

**Comment by Xeaker** [comment]
> The range min/max is mathematically calculated to be -1 to 1, depending on the noise type it can be very rare to even get close to the range limits but it is still theoretically possible

Yeah, because I made like anything between 0.9 and 1 snow area.
So I was confused why I never spawn snow lol
