### ISSUE TITLE
GCC -Waggressive-loop-optimizations Undefined Behavior

### ISSUE THREAD

**Issue by weigert** [Auburn/FastNoiseLite#113]
Hi!

First of all, thank you very much for this library. I have been using it for a long time now as my primary source of noise since it was recommended to me by @KdotJPG.

I have a question about the C++ single-header version, compiling with `GCC` on an M2 Mac (although I believe that I have seen this on other platforms as well). Specifying the `-O2` flag in `GCC`implies the `-Waggressive-loop-optimizations` flag, which does what it states. This leads to the following (exemplary, actually 3x) compiler warning (used in my project `soillib`), and I was curious if this is a known issue:

```
/opt/homebrew/include/soillib/external/FastNoiseLite.h:1691:33: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
 1691 |                         zPrimed += PrimeZ;
      |                         ~~~~~~~~^~~~~~~~~
/opt/homebrew/include/soillib/external/FastNoiseLite.h:1674:46: note: within this loop
 1674 |                     for (int zi = zr - 1; zi <= zr + 1; zi++)
      |                                           ~~~^~~~~~~~~
```

I ignored this for a long time but decided to investigate, and found that the setup of the iteration would indeed trigger an integer overflow, which according to GCC is undefined behavior (the compiler unwinds the loop and finds that it is doing an overflow operation). Is this intentional or documented anywhere? I am not particularly familiar with the algorithm, so since it "just works", I assume that I am missing something. I am opening this issue to document this warning and perhaps provide context (should the behavior be intended).

The overflow in question:

```c++
// Integer Constant (Larger than Half of INT_MAX: 2147483647)
static const int PrimeZ = 1720413743;
// ...
float SingleCellular(int seed, FNfloat x, FNfloat y, FNfloat z) const {
//...
int zr = FastRound(z);
//...
        int zPrimedBase = (zr - 1) * PrimeZ;
//...
                    int zPrimed = zPrimedBase;
                    for (int zi = zr - 1; zi <= zr + 1; zi++){
                      // ...
                      zPrimed += PrimeZ;
                    }
}
```

Assuming that `FNfloat z` is in `[-0.5, 0.5]`, `z` is at minimum `-zPrimedBase`, and after three iterations will necessarily overflow. If it is lower than `-0.5`, then it will necessarily underflow. Am I missing something?

Apologies if this is duplicate.

**Comment by Auburn** [comment]
Yes it is expected to overflow, it needs to match the behaviour of int multiply.

It could also be done like this:
```
int zPrimed = zPrimedBase;
for (int zi = zr - 1; zi <= zr + 1; zi++){
    // ...
    zPrimed = zi * PrimeZ;
}
```
But int multiply is slower than int addition
