### ISSUE TITLE
Inconsistent Cellular Jitter

### ISSUE THREAD

**Issue by ForeverZer0** [Auburn/FastNoiseLite#115]
Different language implementations use an inconsistent constant value for calculating the cellular jitter with the Cellular algorithm. This results in inconsistent outputs with the exact same inputs depending on the language used.  This is of course inconsequential in practice, as it is very unlikely for a single project to be using two different languages to accomplish the same task. I ran into it by chance while creating a Go implementation that was based on the C variant, but testing against the C# version for accuracy, which I would classify as an edge case.

I felt it might be worth mention just for maintaining parity between implementations.

C
```c
float cellularJitter = 0.5f * state->cellular_jitter_mod;
```
GLSL
```glsl
float cellularJitter = 0.5f * state.cellular_jitter_mod;
```
HLSL
```hlsl
float cellularJitter = 0.5f * state.cellular_jitter_mod;
```
C++
```csharp
float cellularJitter = 0.43701595f * mCellularJitterModifier;
```
C++
```cpp
float cellularJitter = 0.43701595f * mCellularJitterModifier;
```
Java
```java
float cellularJitter = 0.43701595f * mCellularJitterModifier;
```
JavaScript
```javascript
let cellularJitter = 0.43701595 * this._CellularJitterModifier;
```

**Comment by Auburn** [comment]
Thanks for finding this, looks like an oversight. The values for 3D jitter match
