### ISSUE TITLE
&fnlFractalGain should be &fnlDomainWarpFractalGain

### ISSUE THREAD

**Issue by Sabrejack** [Auburn/FastNoiseLite#131]
https://github.com/Auburn/FastNoiseLite/blob/8e296acf13e73ba3bc0cc1bc151dc9d95bed0c20/WebPreviewApp/main.cpp#L246

Slider is not functioning properly in the demo, I believe this line is meant to be &fnlDomainWarpFractalGain 

Thanks!

**Comment by Auburn** [comment]
Thanks, fixed with https://github.com/Auburn/FastNoiseLite/commit/93e86db66b3e43944bb493a99ecbdd6cd78676ff
