### ISSUE TITLE
2 frequency parameters in web app, but only one exposed in code

### ISSUE THREAD

**Issue by istinnstudio** [Auburn/FastNoiseLite#132]
Maybe I am totally wrong but, I see 2 frequency parameters a general one and a domain warp one. I am using java version and I will make my own gui for all available parameters,  so when I see 2 frequency parameters in web app, I see only one in the code. Is this normal? thanks

**Comment by Auburn** [comment]
The domain warp uses a second FastNoise object, the code for the web preview app can be found here: https://github.com/Auburn/FastNoiseLite/blob/master/WebPreviewApp/main.cpp
