### ISSUE TITLE
HLSL results different from FastNoise2 (SIMD) results

### ISSUE THREAD

**Issue by Hideman85** [Auburn/FastNoiseLite#145]
Dear @Auburn,

I would like to know if HLSL and FastNoise2 SIMD could produce the exact same values given the same parameters?

My use case is to use it for procedural terrain generator and since all recent PC have both a dedicated GPU and an integrated GPU I would like to use HLSL compute shader on iGPU when possible and fallback to SIMD on CPU when not (for instance, server side or old PCs).

I tried on my `AMD Ryzen 9 7940HS w/ Radeon 780M Graphics` and the difference is huge. But the results differs.
```
// For 4096 * 4096 2D OpenSimplex2
Compute shader took : 0.117000 ms
SIMD took : 2462.604980 ms
```

I checked if this was an issue from my implementation but when using `NoiseTool` and [your example website](https://auburn.github.io/FastNoiseLite/) and the results differ as well.
![image](https://github.com/user-attachments/assets/73c6ab2c-21bf-4534-9cc4-903455af3019)

Would love to get the same values 🙏

EDIT: Additionally do you think we could build the same SmartNode tree in HLSL?

**Comment by Auburn** [comment]
The 2 libraries use different hashing functions for performance reasons. If you brought the FN2 hashing function over to FNL they should give the same output. I remember that someone in the past had done this already, it was discussed on discord. 

Unrelated but the problem with your plan is that most iGPUs get disabled when running a dedicated GPU, unless explicitly enabled in bios

**Comment by Auburn** [comment]
In FN2 `HashPrimesHB` is used for cellular noise and domain warping, so you'd need implement that too if you need those to match. But otherwise you just need to convert `HashPrimes` and `GradCoord` functions you posted above to HLSL
