### ISSUE TITLE
Declaration error in myNoise object

### ISSUE THREAD

**Issue by Underbrine** [Auburn/FastNoiseLite#28]
Hello people !
I wanted to ask you a question because i have a problem while i'm getting started with
the plug in FastNoise in C++.
I am a beginner so sorry if the issue is simple ^^'
The problem is when i ask to my program
`myNoise.SetNoiseType(FastNoise::SymplexFractal);`
the error say "This declaration has no storage class or type specified.
Here is my code :

`#include "FastNoise.h"
#include<iostream>
using namespace std;
FastNoise myNoise; // Create a FastNoise object
myNoise.SetNoiseType(FastNoise::SymplexFractal);
int main() {
	float heightMap[32][32];
	
	for (int x = 0; x < 32; x++)
	{
		for (int y = 0; y < 32; y++)
		{
			heightMap[x][y] = myNoise.GetNoise(x, y);
		}
	}
}`
Thanks for helping i will search on my side ! :)

**Comment by Auburns** [comment]
You spelt Simplex wrong in FastNoise::SymplexFractal

**Comment by Underbrine** [comment]
> 
> 
> You spelt Simplex wrong in FastNoise::SymplexFractal

i correct it but te error is the same... Sorry for the incompetence

**Comment by Auburns** [comment]
Could you please post your full main.cpp

**Comment by Underbrine** [comment]
Ho i saw the error i just needed to type it into the main() function. It rest some errors but i will correct it

**Comment by Underbrine** [comment]
> 
> 
> Could you please post your full main.cpp

`#include "FastNoise.h"
#include<iostream>
using namespace std;

int main() {
	FastNoise myNoise;

	myNoise.SetNoiseType(FastNoise::SimplexFractal);
	float heightMap[32][32];
	
	for (int x = 0; x < 32; x++)
	{
		for (int y = 0; y < 32; y++)
		{
			heightMap[x][y] = myNoise.GetNoise(x, y);
		}
	}
}`
there it is
