### ISSUE TITLE
Kaspersky detecting .dll of live app as a virus.

### ISSUE THREAD

**Issue by Ckblck** [Auburn/FastNoiseLite#65]
The FastNoiseLite.dll files of both releases "FastNoiseLite-1.0.1.zip" and "FastNoiseLite-1.0.2.zip" are being detected as "VHO:Trojan-Banker.MSIL.Convagent.gen" by the **heuristic analysis** of Kaspersky.

Here's a link to VirusTotal, it seems Kaspersky didn't detect it there: https://www.virustotal.com/gui/file/40467b29a97d2167f793a0541c1737232e5aa9eaa65d3d3332a0ec6f21abdce1/detection

![Capture](https://user-images.githubusercontent.com/59627842/106800206-ed4a3100-663e-11eb-96ee-d45203c4f562.PNG)

I'm pretty sure it's a false positive, but it would be nice if this could be fixed to avoid future worries. Although I'm a little bit confused because a few days ago I downloaded the 1.0.1 release and I couldn't find it anymore. But as I said, the .dll of the 1.0.2 version is still being detected as a virus either way.

Thanks! =)

**Comment by Auburn** [comment]
There's not much that I can do about this I don't think. The GUI code isn't very complex, does Kaspersky dislike all .NET Core apps?

**Comment by Ckblck** [comment]
Pretty sure it has some similarity with the code viruses have, so that might be the problem (i'm not a .NET developer so I might be wrong).

But I have found a thread which talks about it, and there is also a solution.

https://stackoverflow.com/questions/65916286/c-sharp-application-detected-by-kaspersky-as-trojan-virus-vhotrojan-msil-conva

**Comment by Ckblck** [comment]
Kaspersky seems to be no longer falsely detecting the latest release, so I'll be closing the issue :).
