### ISSUE TITLE
Add way to change from int seed to long seed

### ISSUE THREAD

**Issue by BudgetToaster** [Auburn/FastNoiseLite#73]
I'm using FastNoiseLite in Java, and would like to use the same seed for both a Java `Random` class instance, and for FastNoiseLite. Obviously, I can convert the long to an int, and make overflows a feature, but for the sake of consistency and variety, it would be appreciated if there was a mechanism similar to that which is used for swapping floats and doubles.

*Just realized that this has been asked before, so apologies for that.

**Comment by Auburn** [comment]
Adding long seeds would slow down the noise generation and there is no easy
way to add it as an extra anyway. Either the code would need to be changed
to always use long seeds or a copy of most the functions would be required
to support both seed types, neither option is feasible.

My suggestion would be to fold the long seed into an int. 'long ^ (long >>
32)'

**Comment by BudgetToaster** [comment]
Ok, I will fold it.
