### ISSUE TITLE
Missing Methods?

### ISSUE THREAD

**Issue by Stanlyhalo** [Auburn/FastNoiseLite#88]
Not entirely sure if this is on purpose, or I can't just find where it is, but in the GUI app form, there's input fields like the Domain Warp Frequency, but that doesn't appear to be something we can change (at least for c#), am I missing something? Is it called something different or just not there?

**Comment by Stanlyhalo** [comment]
While attempting to make a texture in c# from the values I got through the GUI app, it does appear that everything in the image shown aren't in functions/methods except for the domain warp type, and domain warp amplitude, everything else there isn't a method.

**Comment by Stanlyhalo** [comment]
I attempted to make this texture (texture made from the GUI executable):
![image](https://user-images.githubusercontent.com/36088749/156245863-806a46ab-7e65-4bbc-90a4-05d22554f7a9.png)
But even though I used all the same values in the api version, when I set each pixel to the x & y coordinate data, it came out looking like this:
![image](https://user-images.githubusercontent.com/36088749/156246092-1704235f-9e36-473f-b1cb-44032dddd8ed.png)
If you're wondering, these are the properties I set in the GUI application:
![image](https://user-images.githubusercontent.com/36088749/156246152-99703355-319b-4a61-be86-2ef1fe8a9d07.png)
And these are the values made in the api (c#):
```cs
FastNoiseLite noise = new FastNoiseLite();
noise.SetNoiseType(FastNoiseLite.NoiseType.Value);
noise.SetSeed(100);
noise.SetFrequency(0.05f);
noise.SetFractalType(FastNoiseLite.FractalType.PingPong);
noise.SetFractalOctaves(1);
noise.SetFractalLacunarity(3.2f);
noise.SetFractalGain(1.8f);
noise.SetFractalWeightedStrength(0.1f);
noise.SetFractalPingPongStrength(0.4f);
noise.SetDomainWarpType(FastNoiseLite.DomainWarpType.OpenSimplex2);
noise.SetDomainWarpAmp(80f);
```

**Comment by Auburn** [comment]
You need a separate FastNoiseLite instance for domain warping. The missing methods you mentioned are referencing the standard methods but on the domain warp instance.

**Comment by Stanlyhalo** [comment]
Oooh, but than how would I go about mixing the domain warping instance and my main noise instance?

**Comment by Auburn** [comment]
You can see how it's done here in the preview app: https://github.com/Auburn/FastNoiseLite/blob/6be3d6bf7fb408de341285f9ee8a29b67fd953f1/PreviewApp/FastNoiseLiteGUI.cs#L540

**Comment by Stanlyhalo** [comment]
Awesome! Thanks so much, that makes so much more sense now! Worked like a charm.
![image](https://user-images.githubusercontent.com/36088749/156253030-5f99c983-e5c3-46da-ae70-1fc9e2681436.png)
