### ISSUE TITLE
npm package appears to be out of date

### ISSUE THREAD

**Issue by DylanCulfogienis** [Auburn/FastNoiseLite#93]
The JavaScript NPM package located at https://www.npmjs.com/package/fastnoise-lite appears to be out of date. The latest tag as of writing on GitHub is 1.0.3, while npm is still at 0.0.1.

**Comment by Auburn** [comment]
Fixed with [v1.1.0](https://github.com/Auburn/FastNoiseLite/releases/tag/v1.1.0)
