### ISSUE TITLE
64-bit Windows executable version FastNoiseLite is infected by virus BankerX-gen

### ISSUE THREAD

**Issue by oculus99** [Auburn/FastNoiseLite#94]
My antivirus program says that FastNoiseLite windows version has 
virus infection.

https://github.com/Auburn/FastNoiseLite/releases

Infected program is

https://github.com/Auburn/FastNoiseLite/releases/download/v1.0.3/FastNoiseLiteGUI-Win64.exe

**Comment by oculus99** [comment]
Infector is Win64:BankerX-gen [Trj].

Can you please recompile your program or remove virus with other ways.

**Comment by Auburn** [comment]
This is most likely a false positive with your anti-virus software. Virus total shows only a few positives: https://www.virustotal.com/gui/file/30aa4e42a169c6f6b5caf668c64308452cd881aefba085bb7671a23eb2be0f14

If you are still worried you can compile the GUI tool yourself
